/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IArtifactNft } from "./IArtifactNft";
export type { IEquipmentNft } from "./IEquipmentNft";
export type { IJobNft } from "./IJobNft";
