/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lootNfts from "./lootNfts";
export type { lootNfts };
export type { IArmourNft } from "./IArmourNft";
export type { IERC6551Account } from "./IERC6551Account";
export type { IERC6551Registry } from "./IERC6551Registry";
export type { ISoulCalculator } from "./ISoulCalculator";
export type { ISoulMinter } from "./ISoulMinter";
export type { ISoulNft } from "./ISoulNft";
