/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISoulCalculator,
  ISoulCalculatorInterface,
} from "../../../contracts/interfaces/ISoulCalculator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nft_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "seedData_",
        type: "bytes",
      },
    ],
    name: "calcArtifact",
    outputs: [
      {
        internalType: "uint256",
        name: "_seed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_artifactType",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_rarity",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nft_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "seedData_",
        type: "bytes",
      },
    ],
    name: "calcEquipment",
    outputs: [
      {
        internalType: "uint256",
        name: "_seed",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "_equipmentIds",
        type: "uint256[8]",
      },
      {
        internalType: "string[8]",
        name: "_equipmentNames",
        type: "string[8]",
      },
      {
        internalType: "uint256[8]",
        name: "_equipmentRarities",
        type: "uint256[8]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nft_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "seedData_",
        type: "bytes",
      },
    ],
    name: "calcJob",
    outputs: [
      {
        internalType: "uint256",
        name: "_seed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_jobType",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nft_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "seedData_",
        type: "bytes",
      },
    ],
    name: "calcSoul",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "uint256",
                name: "seed",
                type: "uint256",
              },
              {
                internalType: "uint8[]",
                name: "directions",
                type: "uint8[]",
              },
              {
                internalType: "uint8[]",
                name: "useItems",
                type: "uint8[]",
              },
            ],
            internalType: "struct ILootByRogueV2.InputData",
            name: "inputData",
            type: "tuple",
          },
          {
            internalType: "uint16",
            name: "turn",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "maxHp",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "currentHp",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "attack",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "defence",
            type: "uint16",
          },
          {
            internalType: "uint16",
            name: "recovery",
            type: "uint16",
          },
          {
            internalType: "uint16[6]",
            name: "stats",
            type: "uint16[6]",
          },
          {
            internalType: "uint8[4]",
            name: "unique",
            type: "uint8[4]",
          },
          {
            internalType: "uint256",
            name: "weapon",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "chestArmor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "headArmor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "waistArmor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "footArmor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "handArmor",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "necklace",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "ring",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "relics",
            type: "uint256[]",
          },
        ],
        internalType: "struct ILootByRogueV2.AdventureRecord",
        name: "_record",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISoulCalculator__factory {
  static readonly abi = _abi;
  static createInterface(): ISoulCalculatorInterface {
    return new utils.Interface(_abi) as ISoulCalculatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISoulCalculator {
    return new Contract(address, _abi, signerOrProvider) as ISoulCalculator;
  }
}
