import { ConnectButton } from '@rainbow-me/rainbowkit';
import { Box, Button, Flex, Heading, Image, Text } from '@chakra-ui/react';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, usePrepareContractWrite, useContractWrite, useWaitForTransaction} from 'wagmi';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Loot-Adventure Demo APp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <Button
            margin={4}
            padding={2}
            cursor="pointer"
            color={'white'}
            backgroundColor={'blue'}
            onClick={() => router.push(`/write_sample_loot`)}
            _hover={{ transform: 'scale(1.05)' }}
        >
          01_Mint_SampleLoot
        </Button>

        <Button
            margin={4}
            padding={2}
            cursor="pointer"
            color={'white'}
            backgroundColor={'blue'}
            onClick={() => router.push(`/write_soul_loot`)}
            _hover={{ transform: 'scale(1.05)' }}
        >
          02_Mint_Soul-Loot
        </Button>

        <Button
            margin={4}
            padding={2}
            cursor="pointer"
            color={'white'}
            backgroundColor={'blue'}
            onClick={() => router.push(`/write_create_soul`)}
            _hover={{ transform: 'scale(1.05)' }}
        >
          03_Create_SoulNfts
        </Button>
      </main>
    </div>
  );
};

export default Home;
